spring:
  application:
    name: spring-laboratory-work
  # DB properties
  datasource:
    read:
      username: user
      password: user
      url: jdbc:postgresql://localhost:5432/postgres
      driver-class-name: org.postgresql.Driver
    write:
      username: user1
      password: user1
      url: jdbc:postgresql://localhost:5434/postgres
      driver-class-name: org.postgresql.Driver
  #JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true

  #FlyWay properties
  flyway:
    enabled: true
    baseline-on-migrate: true

# Logging level
logging:
  level:
    org.springframework.data.org.springframework.data.jpa: debug
    org.flywaydb: DEBUG