spring:
  application:
    name: spring-laboratory-work
  datasource:
    read:
      username: postgres
      password: admin123123
      jdbc-url: jdbc:postgresql://project-rds-postgres-read-replica.c10gk4a0c4tn.eu-central-1.rds.amazonaws.com:5432/project_db
      driver-class-name: org.postgresql.Driver
    write:
      username: postgres
      password: admin123123
      jdbc-url: jdbc:postgresql://project-rds-postgres-prod.c10gk4a0c4tn.eu-central-1.rds.amazonaws.com:5432/project_db
      driver-class-name: org.postgresql.Driver

  # Flyway properties
  flyway:
    enabled: false
  custom-flyway:
    read:
      username: postgres
      password: admin123123
      jdbc-url: jdbc:postgresql://project-rds-postgres-read-replica.c10gk4a0c4tn.eu-central-1.rds.amazonaws.com:5432/project_db
      driver-class-name: org.postgresql.Driver
    write:
      username: postgres
      password: admin123123
      jdbc-url: jdbc:postgresql://project-rds-postgres-prod.c10gk4a0c4tn.eu-central-1.rds.amazonaws.com:5432/project_db
      driver-class-name: org.postgresql.Driver


# Logging level
logging:
  level:
    org.springframework.data.jpa: DEBUG
    org.flywaydb: DEBUG
server:
  port: 8080
  address: 0.0.0.0
